#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-sveltekit-node-buffer"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = ".svelte-kit/cloudflare"
